namespace GroqNet.ChatCompletions;

/// <summary>
/// Represents the usage statistics of a processing request, including details about tokens used and the time taken for processing.
/// </summary>
public class GroqUsage
{
    /// <summary>
    /// Represents the number of tokens used in the prompt portion of the request
    /// </summary>
    public required int PromptTokens { get; set; }

    /// <summary>
    /// Represents the number of tokens generated by the model in response to the prompt
    /// </summary>
    public required int CompletionTokens { get; set; }

    /// <summary>
    /// Total number of tokens involved in both the prompt and the completion
    /// </summary>
    public required int TotalTokens { get; set; }

    /// <summary>
    /// Time taken (in seconds) to process the prompt
    /// </summary>
    public required decimal PromptTime { get; set; }

    /// <summary>
    /// Time taken (in seconds) to generate the completion response
    /// </summary>
    public required decimal CompletionTime { get; set; }

    /// <summary>
    /// Total time (in seconds) taken from receiving the prompt to providing the completion
    /// </summary>
    public required decimal TotalTime { get; set; }
}